### ISSUE TITLE
Search is slow

### ISSUE THREAD

**Issue by samanthasunne** [hackshackers/hackshackers-hugo#110]
Search results take 2-3 seconds if it's your first time doing a search on that site or browser. After you do it once, the search is pretty much instant

**Comment by joshkadis** [comment]
Because of the way the site is built and hosted, search requires downloading a file that's basically a compressed index of all the searchable content on the site. 

There's a lot of content on the site, so it's a big file that takes a couple of seconds to download after the user submits a search request. It's also big enough that we wouldn't want to preemptively download it in the background because of bandwidth.

The only way to make search faster is to reduce the size of the index file, which would mean reducing the amount of content available to search. Maybe exclude posts before a certain date?

**Comment by samanthasunne** [comment]
If it would be a lot of work to change it, let's just leave it as is
